### PR TITLE
provide random

### PR DESCRIPTION
**Pull request by ghost**
Used in section 1.2.6. While here, alphabetize required procedures.

### CODE REVIEW

**Comment by soegaard** [comment]
It is a good idea to add `random`. The `random` used in SICP (and MIT Scheme) is slightly different from the one in Racket though. See:

    https://github.com/sicp-lang/sicp/issues/6

Will you make a new pull request with this slightly different `random` ?

**Comment by ghost** [comment]
I've looked at the issue and updated this pull request with a new commit. Please let me know if additional changes are required.

**Comment by soegaard** [comment]
Thanks!

**Comment by soegaard** [comment]
Reopening.

**Pull request closed without merging**
