### PR TITLE
Update main.rkt

### PR DESCRIPTION
**Pull request by zzz6519003**

### CODE REVIEW

**Comment by soegaard** [comment]
This commit adds stream-car, stream-cdr and stream-map.
These functions are defined in section "3.5.1  Streams Are Delayed Lists",
so the reader is supposed to add these himself.

The construct `cons-stream` on the other hand is not expected to
be defined by a reader, since it is not a function (and SICP doesn't
include a section on macros).

**Comment by cwfoo** [comment]
@zzz6519003 See rejected pull request #16.

**Comment by zzz6519003** [comment]
gj!

**Comment by soegaard** [comment]
Since two people took the time to report the missing functions and make a pull request, maybe we should add them anyway?  Or at least mention them in the documentation?

What do you guys think?

**Comment by cwfoo** [comment]
I think we should add `stream-car` and `stream-cdr` only. 

Reasons in favour:

* In people's minds, `cons`, `car` and `cdr` go together. 
* The implementations of `car-stream` and `cdr-stream` are trivial. Not much experience will be lost even if a student does not write his/her own implementation. `delay` and `force` are mentioned so many times that it's impossible to not know how they work.
*  `stream-car` and `stream-cdr` are used from the beginning to the end of section 3.5 (Streams) as fundamental building blocks for procedures far more interesting than `stream-car` and `stream-cdr`.

I think we can make an exception to the rule for these procedures.

**Pull request closed without merging**
